/**:
  ros__parameters:
    moveit_cpp:
      planning_scene_monitor_options:
        name: "psm"
        publish_planning_scene: true
        publish_geometry_updates: true
        publish_state_updates: true
        publish_transforms_updates: true

      planning_pipelines: ["isaac_ros_cumotion", "ompl"]   # pick what you have
      default_planning_pipeline: "ompl"

    one_arm_nbv_bt:
      controllers:
        cm_ns: ""                      # e.g. "fr3" if you run namespaced
        # Typical MoveIt controller (edit to match your system):
        #   - arm trajectory controller exposed to MoveIt
        #   - your impedance / hand-guiding controller (example names!)
        moveit_arm_controller: "fr3_arm_controller"
        handguide_controller:  "cartesian_impedance_controller"

      # Center for the object 
      object_center:
        frame: nbv_object_center
        rebroadcast_ms: 200

        object_center_pose:
          frame_id: "base"
          xyz: [0.35, 0.0, 0.10]
          rpy: [0.0, 0.0, 0.0]

      # setup planner used by MoveIt2
      pipeline_id: ""                   # or "isaac_ros_cumotion" etc. (empty = use move_group default)
      planner_id:  "RRTConnectkConfigDefault" # "RRTConnectkConfigDefault"

      group_name: "fr3_arm"     
      ee_link:   "fr3_hand"
      gripper_ns: "franka_gripper"         
      tcp_link:  "fr3_hand_tcp"

      # pick (close)
      grasp:
        width: 0.001 # 0.005 # 0.030
        speed: 0.10
        force: 20.0
        eps_inner: 0.005
        eps_outer: 0.005

      # place (open)
      open:
        width: 0.080
        speed: 0.10

      # optional proxy object behavior (for nbv planning)
      attach_proxy: false
      detach_proxy: false
      proxy_radius: 0.03



      pre_pick_pose:
        frame_id: "base"
        xyz: [0.45, 0.20, 0.45]
        rpy: [3.14159, 0.00, 0.45]

      pick_pose:
        frame_id: "base"
        xyz: [0.45, 0.20, 0.18]
        rpy: [3.14159, 0.00, 0.45]

      pre_place_pose:
        frame_id: "base"
        xyz: [0.4, -0.10, 0.45]
        rpy: [3.14159, 0.00, 0.45]

      place_pose:
        frame_id: "base"
        xyz: [0.4, -0.10, 0.2]
        rpy: [3.14159, 0.00, 0.45]

      home:
        names:     ["fr3_joint1","fr3_joint2","fr3_joint3","fr3_joint4","fr3_joint5","fr3_joint6","fr3_joint7"]
        positions: [ 0.0, -0.785398, 0.0, -2.35619, 0.0, 1.5708, 0.45 ]

      # Camera related params
      nbv_srv:   "/nbv/compute"      # plug your service here
      fuse_srv:  "/fusion/fuse"
      coverage_threshold: 0.99

      sample:
        # Camera IO
        camera:
          topic: "/camera/camera/depth/color/points"   # RealSense organized point cloud
          working_frame: "base"                 # transform cloud into this frame
          publish_topic: "/nbv/filtered_cloud"  # output topic
          voxel_leaf: 0.0                      # 0 disables voxel downsampling

        # Desk removal (z>height+margin in working_frame)
        desk:
          enable: true
          height: 0.0
          margin: 0.012

        # ROI cropping
        roi:
          box:                    # one arm test
            enable: true
            min: [ 0.2, -0.15, 0.00]
            max: [ 0.5,  0.15, 0.20]
          sphere:
            enable: false
            frame: "fr3_hand"     # center on TCP (or provide any frame)
            radius: 0.30

        # Robot masking
        robot_mask:
          enable: false
          mode: "spheres"         # "spheres" or "mesh"

          # Spherical masks (used when mode=="spheres")
          frames: ["fr3_link2", "fr3_link3", "fr3_link4", "fr3_link5", "fr3_hand"]
          radii:  [ 0.09,        0.09,        0.09,        0.08,        0.07     ]

          # Mesh mask settings (used when mode=="mesh")
          mesh_probe_radius: 0.01   # m, sphere probe for FCL collision tests

        # Attached-object mask near TCP
        attached_mask:
          enable: true
          radius: 0.05

        # Where to read joint states for mesh masking
        joint_states_topic: "/joint_states"   

        save:
          enable: true
          dir: /tmp/nbv_scans
          prefix: filtered
          ascii: false
        nbv_service:
          name: /nbv_ros2_node_trigger 

      fuse:
        input_topic: "/nbv/filtered_cloud"   # from CameraSample
        map_topic:   "/nbv/global_map"
        aligned_topic: "/nbv/aligned_cloud"
        map_frame:   "base"

        # Downsampling
        input_leaf: 0.0       # m (downsample incoming scans)
        map_leaf:   0.0       # m (downsample after merge)

        # ICP / GICP
        icp:
          use_gicp: true
          max_iter: 50
          max_corr_dist: 0.05     # m
          trans_eps: 1.0e-6
          fitness_eps: 1.0e-6
          max_fitness: 0.01       # reject merge if worse than this

        # Behavior
        reset_on_empty: false
        save_pcd_on_success: false
        save_pcd_path: "/tmp/nbv_global_map.pcd"

        nbv_service:
          name: /nbv_ros2_node_trigger 

      eval:
        enable: true
        reference_file: "/home/robot/ref_models/object_ref.pcd"   # or .stl
        reference_type: "auto"     # auto|pcd|stl
        sample_points: 100000      # for STL
        leaf_map: 0.0              # 0 = no ds
        leaf_ref: 0.0
        dist_thresh: 0.01          # m
